### ISSUE TITLE
token recognition error 导致重启失败

### ISSUE THREAD

**Issue by jqlin2019** [TuGraph-family/tugraph-db#319]
因网络故障导致客户端和图数据库断开，客户端自动重连后认证失败，并导致图数据库下线，是否可能是token过期导致的呢

操作系统ubuntu18.04 LTS, docker-compose的配置如下：
```
version: '3'
services:
  tugraph:
    restart: always
    image: tugraph-runtime-centos7:3.5.0
    container_name: tugraph-database-3.5.0
    volumes:
      - ./lgraph_data:/var/lib/lgraph/data
      - ./lgraph_log:/var/log/lgraph_log
    ports:
      - 7070:7070
      - 9090:9090
    command: "lgraph_server"
```

docker log 报错如下：
```
line 1:268 token recognition error at: '&'
...
line 1:278 token recognition error at: '!'
```
